variables:
  MONGODB_VERSION: '4.2.3'

trigger:
  - master
jobs: []

  # - job: Ubuntu_18
  #   pool:
  #     vmImage: 'ubuntu-18.04'
  #   steps:
  #     - script: |
  #         set -e
  #       displayName: 'Install Services'
  #     - task: NodeTool@0
  #       inputs:
  #         versionSpec: '12.4.0'
  #       displayName: 'Install Node.js'
  #     - script: |
  #         npm install --global npm@latest
  #         npm install --global lerna
  #       displayName: 'Install Global Packages'
  #     - script: |
  #         npm run bootstrap
  #       displayName: 'Bootstrap'
  #     - script: |
  #         npm run check
  #       displayName: 'Run Checks'
  #     - script: |
  #         npm run test-ci
  #       displayName: 'Run Tests'
  #     - script: |
  #         npm run compile-exec
  #       displayName: 'Build REPL'
  #     - publish: $(System.DefaultWorkingDirectory)/dist
  #       artifact: binaries
  #       displayName: 'Publish Binaries'

  # - job: Ubuntu_16
  #   pool:
  #     vmImage: 'ubuntu-16.04'
  #   steps:
  #     - script: |
  #         set -e
  #       displayName: 'Install Services'
  #     - task: NodeTool@0
  #       inputs:
  #         versionSpec: '12.4.0'
  #       displayName: 'Install Node.js'
  #     - script: |
  #         npm install --global npm@latest
  #         npm install --global lerna
  #       displayName: 'Install Global Packages'
  #     - script: |
  #         npm run bootstrap
  #       displayName: 'Bootstrap'
  #     - script: |
  #         npm run check
  #       displayName: 'Run Checks'
  #     - script: |
  #         npm run test-ci
  #       displayName: 'Run Tests'

  # - job: MacOS_Mohave
  #   pool:
  #     vmImage: 'macOS-10.14'
  #   steps:
  #     - task: NodeTool@0
  #       inputs:
  #         versionSpec: '12.4.0'
  #       displayName: 'Install Node.js'
  #     - script: |
  #         npm install --global npm@latest
  #         npm install --global lerna
  #       displayName: 'Install Global Packages'
  #     - script: |
  #         npm run bootstrap
  #       displayName: 'Bootstrap'
  #     - script: |
  #         npm run check
  #       displayName: 'Run Checks'
  #     - script: |
  #         npm run test-ci
  #       displayName: 'Run Tests'

  # - job: Windows_Server_2019
  #   pool:
  #     vmImage: 'windows-2019'
  #   steps:
  #     - task: NodeTool@0
  #       inputs:
  #         versionSpec: '12.4.0'
  #       displayName: 'Install Node.js'
  #     - script: |
  #         npm install --global npm@latest
  #         npm install --global lerna
  #       displayName: 'Install Global Packages'
  #     - script: |
  #         npm run bootstrap
  #       displayName: 'Bootstrap'
  #     - script: |
  #         npm run check
  #       displayName: 'Run Checks'
  #     - script: |
  #         npm run test-ci
  #       displayName: 'Run Tests'

  # - job: Windows_Server_2016
  #   pool:
  #     vmImage: 'vs2017-win2016'
  #   steps:
  #     - task: NodeTool@0
  #       inputs:
  #         versionSpec: '12.4.0'
  #       displayName: 'Install Node.js'
  #     - script: |
  #         npm install --global npm@latest
  #         npm install --global lerna
  #       displayName: 'Install Global Packages'
  #     - script: |
  #         npm run bootstrap
  #       displayName: 'Bootstrap'
  #     - script: |
  #         npm run check
  #       displayName: 'Run Checks'
  #     - script: |
  #         npm run test-ci
  #       displayName: 'Run Tests'
