trigger:
  - master
jobs:
  - job: Ubuntu
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - script: |
          set -e
        displayName: 'Install Services'
      - task: NodeTool@0
        inputs:
          versionSpec: '12.4.0'
        displayName: 'Install Node.js'
      - script: |
          npm install --global npm@latest
          npm install --global lerna
        displayName: 'Install Global Packages'
      - script: |
          npm run bootstrap
        displayName: 'Bootstrap'
      - script: |
          npm run check
        displayName: 'Run Checks'
      - script: |
          npm run test-ci
        displayName: 'Run Tests'
        env:
          MONGOSH_STITCH_TEST_APP_ID: $(MONGOSH_STITCH_TEST_APP_ID)
          MONGOSH_STITCH_TEST_SERVICE_NAME: $(MONGOSH_STITCH_TEST_SERVICE_NAME)
  - job: MacOS
    pool:
      vmImage: 'macOS-latest'
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '12.4.0'
        displayName: 'Install Node.js'
      - script: |
          npm install --global npm@latest
          npm install --global lerna
        displayName: 'Install Global Packages'
      - script: |
          npm run bootstrap
        displayName: 'Bootstrap'
      - script: |
          npm run check
        displayName: 'Run Checks'
      - script: |
          npm run test-ci
        displayName: 'Run Tests'
        env:
          MONGOSH_STITCH_TEST_APP_ID: $(MONGOSH_STITCH_TEST_APP_ID)
          MONGOSH_STITCH_TEST_SERVICE_NAME: $(MONGOSH_STITCH_TEST_SERVICE_NAME)
  - job: Windows
    pool:
      vmImage: 'windows-latest'
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '12.4.0'
        displayName: 'Install Node.js'
      - script: |
          npm install --global npm@latest
          npm install --global lerna
        displayName: 'Install Global Packages'
      - script: |
          npm run bootstrap
        displayName: 'Bootstrap'
      - script: |
          npm run check
        displayName: 'Run Checks'
      - script: |
          npm run test-ci
        displayName: 'Run Tests'
        env:
          MONGOSH_STITCH_TEST_APP_ID: $(MONGOSH_STITCH_TEST_APP_ID)
          MONGOSH_STITCH_TEST_SERVICE_NAME: $(MONGOSH_STITCH_TEST_SERVICE_NAME)
