services:
  notary_url: "http://notary-service.build.10gen.cc:5000"

templates:
  deb:
    org: |
      Origin: mongodb
      Label: mongodb
      Suite: {{ .CodeName }}
      Codename: {{ .CodeName }}/mongodb-org
      Architectures: {{ .Architectures }}
      Components: {{ .Component }}
      Description: MongoDB packages
    enterprise: |
      Origin: mongodb
      Label: mongodb
      Suite: {{ .CodeName }}
      Codename: {{ .CodeName }}/mongodb-enterprise
      Architectures: {{ .Architectures }}
      Components: {{ .Component }}
      Description: MongoDB packages
  index_page: |
    <!DOCTYPE html>
    <html>
     <head>
       <title>{{ .Title }}</title>
     </head>
     <body>
       <table>
        <tr><td>
          <h1>{{ .Title }}</h1>
        </td></tr>
        <tr><td>
          <hr>
        </td></tr>
        <tr><td>
          <a href='..'>Parent Directory</a>
        </td></tr>
        {{ range $fn := .Files }}
        <tr><td>
          <a href='{{ $fn }}'>{{ $fn }}</a>
        </td></tr>
        {{ end }}
        <tr><td>
          <hr>
        </td></tr>
        <tr><td>
          <address>{{ .RepoName }}</address>
        </td></tr>
      </table>
     </body>
    </html>
repos:

####################
#
# Community Repos:
#
####################

  - name: debian10
    type: deb
    code_name: "buster"
    bucket: repo.mongodb.org
    edition: org
    component: main
    architectures:
      - amd64
      - arm64
    repos:
      - apt/debian/dists/buster/mongodb-org

  - name: debian11
    type: deb
    code_name: "bullseye"
    bucket: repo.mongodb.org
    edition: org
    component: main
    architectures:
      - amd64
      - arm64
    repos:
      - apt/debian/dists/bullseye/mongodb-org

  - name: debian12
    type: deb
    code_name: "bookworm"
    bucket: repo.mongodb.org
    edition: org
    component: main
    architectures:
      - amd64
      - arm64
    repos:
      - apt/debian/dists/bookworm/mongodb-org

  - name: ubuntu1804
    type: deb
    code_name: "bionic"
    edition: org
    bucket: repo.mongodb.org
    component: multiverse
    architectures:
      - amd64
      - arm64
    repos:
      - apt/ubuntu/dists/bionic/mongodb-org

  - name: ubuntu2004
    type: deb
    code_name: "focal"
    edition: org
    bucket: repo.mongodb.org
    component: multiverse
    architectures:
      - amd64
      - arm64
    repos:
      - apt/ubuntu/dists/focal/mongodb-org

  - name: ubuntu2204
    type: deb
    code_name: "jammy"
    edition: org
    bucket: repo.mongodb.org
    component: multiverse
    architectures:
      - amd64
      - arm64
    repos:
      - apt/ubuntu/dists/jammy/mongodb-org

  - name: ubuntu2404
    type: deb
    code_name: "noble"
    edition: org
    bucket: repo.mongodb.org
    component: multiverse
    architectures:
      - amd64
      - arm64
    repos:
      - apt/ubuntu/dists/noble/mongodb-org

  - name: rhel70
    type: rpm
    edition: org
    bucket: repo.mongodb.org
    architectures:
      - x86_64
      - ppc64le
      - s390x
    repos:
      - yum/redhat/7/mongodb-org
      - yum/redhat/7Server/mongodb-org

  - name: rhel80
    type: rpm
    edition: org
    bucket: repo.mongodb.org
    architectures:
      - x86_64
      - aarch64
      - ppc64le
      - s390x
    repos:
      - yum/redhat/8/mongodb-org
      - yum/redhat/8Server/mongodb-org

  - name: rhel90
    type: rpm
    edition: org
    bucket: repo.mongodb.org
    architectures:
      - x86_64
      - aarch64
      - ppc64le
      - s390x
    repos:
      - yum/redhat/9/mongodb-org
      - yum/redhat/9Server/mongodb-org

  - name: suse12
    type: rpm
    edition: org
    bucket: repo.mongodb.org
    architectures:
      - x86_64
    repos:
      - zypper/suse/12/mongodb-org

  - name: suse15
    type: rpm
    edition: org
    bucket: repo.mongodb.org
    repos:
      - zypper/suse/15/mongodb-org

  - name: amazon1
    type: rpm
    edition: org
    bucket: repo.mongodb.org
    architectures:
      - x86_64
    repos:
      - yum/amazon/2013.03/mongodb-org

  - name: amazon2
    type: rpm
    edition: org
    bucket: repo.mongodb.org
    architectures:
      - arm64
      - x86_64
    repos:
      - yum/amazon/2/mongodb-org

  - name: amazon2023
    type: rpm
    edition: org
    bucket: repo.mongodb.org
    architectures:
      - arm64
      - x86_64
    repos:
      - yum/amazon/2023/mongodb-org

####################
#
# Enterprise Repos:
#
####################

  - name: debian10
    type: deb
    code_name: "buster"
    bucket: repo.mongodb.com
    edition: enterprise
    component: main
    architectures:
      - amd64
      - arm64
    repos:
      - apt/debian/dists/buster/mongodb-enterprise

  - name: debian11
    type: deb
    code_name: "bullseye"
    bucket: repo.mongodb.com
    edition: enterprise
    component: main
    architectures:
      - amd64
      - arm64
    repos:
      - apt/debian/dists/bullseye/mongodb-enterprise

  - name: debian12
    type: deb
    code_name: "bookworm"
    bucket: repo.mongodb.com
    edition: enterprise
    component: main
    architectures:
      - amd64
      - arm64
    repos:
      - apt/debian/dists/bookworm/mongodb-enterprise

  - name: ubuntu1804
    type: deb
    code_name: "bionic"
    edition: enterprise
    bucket: repo.mongodb.com
    component: multiverse
    architectures:
      - amd64
      - arm64
    repos:
      - apt/ubuntu/dists/bionic/mongodb-enterprise

  - name: ubuntu2004
    type: deb
    code_name: "focal"
    edition: enterprise
    bucket: repo.mongodb.com
    component: multiverse
    architectures:
      - amd64
      - arm64
    repos:
      - apt/ubuntu/dists/focal/mongodb-enterprise

  - name: ubuntu2204
    type: deb
    code_name: "jammy"
    edition: enterprise
    bucket: repo.mongodb.com
    component: multiverse
    architectures:
      - amd64
      - arm64
    repos:
      - apt/ubuntu/dists/jammy/mongodb-enterprise

  - name: ubuntu2404
    type: deb
    code_name: "noble"
    edition: enterprise
    bucket: repo.mongodb.com
    component: multiverse
    architectures:
      - amd64
      - arm64
    repos:
      - apt/ubuntu/dists/noble/mongodb-enterprise

  - name: rhel70
    type: rpm
    edition: enterprise
    bucket: repo.mongodb.com
    architectures:
      - x86_64
      - ppc64le
      - s390x
    repos:
      - yum/redhat/7/mongodb-enterprise
      - yum/redhat/7Server/mongodb-enterprise

  - name: rhel80
    type: rpm
    edition: enterprise
    bucket: repo.mongodb.com
    architectures:
      - x86_64
      - aarch64
      - ppc64le
      - s390x
    repos:
      - yum/redhat/8/mongodb-enterprise
      - yum/redhat/8Server/mongodb-enterprise

  - name: rhel90
    type: rpm
    edition: enterprise
    bucket: repo.mongodb.com
    architectures:
      - x86_64
      - aarch64
      - ppc64le
      - s390x
    repos:
      - yum/redhat/9/mongodb-enterprise
      - yum/redhat/9Server/mongodb-enterprise

  - name: suse12
    type: rpm
    edition: enterprise
    bucket: repo.mongodb.com
    architectures:
      - x86_64
    repos:
      - zypper/suse/12/mongodb-enterprise

  - name: suse15
    type: rpm
    edition: enterprise
    bucket: repo.mongodb.com
    repos:
      - zypper/suse/15/mongodb-enterprise

  - name: amazon1
    type: rpm
    edition: enterprise
    bucket: repo.mongodb.com
    architectures:
      - x86_64
    repos:
      - yum/amazon/2013.03/mongodb-enterprise

  - name: amazon2
    type: rpm
    edition: enterprise
    bucket: repo.mongodb.com
    architectures:
      - arm64
      - x86_64
    repos:
      - yum/amazon/2/mongodb-enterprise

  - name: amazon2023
    type: rpm
    edition: enterprise
    bucket: repo.mongodb.com
    architectures:
      - arm64
      - x86_64
    repos:
      - yum/amazon/2023/mongodb-enterprise
